### ISSUE TITLE
Hexlink target net.fabric (...) was loaded too early.

### ISSUE THREAD

**Issue by Ang3l404** [Jempasam/Hexlink#10]
[17:26:02] [main/INFO]: Loading Minecraft 1.19.2 with Fabric Loader 0.15.6
[17:26:02] [ForkJoinPool-1-worker-12/WARN]: Mod inventorytabs uses the version 0.9.beta-1.19.x which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'beta'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[17:26:02] [ForkJoinPool-1-worker-1/WARN]: Mod letmedespawn uses the version fabric-1.0.2 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'fabric'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[17:26:02] [main/INFO]: Loading 221 mods:
	- advancementplaques 1.4.6
	- appleskin 2.5.1+mc1.19
	- architectury 6.5.90
	- attributefix 17.2.7
	- badpackets 0.2.3
	- balm-fabric 4.6.0
	- barteringstation 4.0.3
	- bclib 2.1.8
	- betteradvancements 0.3.0.148
	- bettercombat 1.7.1+1.19
	- betterdeserttemples 1.19.2-Fabric-2.2.2
	   \-- org_reflections_reflections 0.10.2
	- betterdungeons 1.19.2-Fabric-3.2.1
	- betterend 2.1.7
	- betterf3 4.0.1
	   \-- cloth-config 8.2.88
	        \-- cloth-basic-math 0.6.1
	- betterfortresses 1.19.2-Fabric-1.0.6
	- betterjungletemples 1.19.2-Fabric-1.0.1
	- bettermineshafts 1.19.2-Fabric-3.2.1
	- betternether 7.1.5
	- betteroceanmonuments 1.19.2-Fabric-2.1.1
	- betterstrongholds 1.19.2-Fabric-3.2.0
	- bettertridents 4.0.2
	- betterwitchhuts 1.19.2-Fabric-2.1.0
	- blur 2.6.0
	   |-- midnightlib 0.5.2
	   \-- satin 1.8.0
	- bookshelf 16.3.20
	- borderlessmining 1.1.5+1.19
	- cardinal-components 5.0.2
	   |-- cardinal-components-base 5.0.2
	   |-- cardinal-components-block 5.0.2
	   |-- cardinal-components-chunk 5.0.2
	   |-- cardinal-components-entity 5.0.2
	   |-- cardinal-components-item 5.0.2
	   |-- cardinal-components-level 5.0.2
	   |-- cardinal-components-scoreboard 5.0.2
	   \-- cardinal-components-world 5.0.2
	- clumps 9.0.0+14
	- collective 7.30
	- connectiblechains 2.1.4+1.19.2
	- craftingtweaks 15.1.9
	- diagonalfences 4.2.6
	- dynamic_fps 3.3.3
	- easyanvils 4.0.11
	- easymagic 4.3.3
	- elytraslot 6.1.1+1.19.2
	- enchdesc 13.0.14
	- entityculling 1.6.1-mc1.19.2
	- essential-container 1.0.0
	   \-- essential-loader 1.2.1
	- fabric-api 0.77.0+1.19.2
	   |-- fabric-api-base 0.4.15+8f4e8eb390
	   |-- fabric-api-lookup-api-v1 1.6.14+93d8cb8290
	   |-- fabric-biome-api-v1 9.1.1+16f1e31390
	   |-- fabric-block-api-v1 1.0.2+e415d50e90
	   |-- fabric-blockrenderlayer-v1 1.1.25+cafc6e8e90
	   |-- fabric-client-tags-api-v1 1.0.5+b35fea8390
	   |-- fabric-command-api-v1 1.2.16+f71b366f90
	   |-- fabric-command-api-v2 2.2.1+413cbbc790
	   |-- fabric-commands-v0 0.2.33+df3654b390
	   |-- fabric-containers-v0 0.1.42+df3654b390
	   |-- fabric-content-registries-v0 3.5.2+7c6cd14d90
	   |-- fabric-convention-tags-v1 1.3.0+4bc6e26290
	   |-- fabric-crash-report-info-v1 0.2.8+aeb40ebe90
	   |-- fabric-data-generation-api-v1 5.3.9+413cbbc790
	   |-- fabric-dimensions-v1 2.1.35+0d0f210290
	   |-- fabric-entity-events-v1 1.5.4+9244241690
	   |-- fabric-events-interaction-v0 0.4.34+562bff6e90
	   |-- fabric-events-lifecycle-v0 0.2.36+df3654b390
	   |-- fabric-game-rule-api-v1 1.0.24+b6b6abb490
	   |-- fabric-item-api-v1 1.6.6+b7d1888890
	   |-- fabric-item-groups-v0 0.3.39+9244241690
	   |-- fabric-key-binding-api-v1 1.0.25+5c4fce2890
	   |-- fabric-keybindings-v0 0.2.23+df3654b390
	   |-- fabric-lifecycle-events-v1 2.2.4+1b46dc7890
	   |-- fabric-loot-api-v2 1.1.13+83a8659290
	   |-- fabric-loot-tables-v1 1.1.16+9e7660c690
	   |-- fabric-message-api-v1 5.0.7+93d8cb8290
	   |-- fabric-mining-level-api-v1 2.1.24+33fbc73890
	   |-- fabric-models-v0 0.3.21+c6af733c90
	   |-- fabric-networking-api-v1 1.2.12+def3f86d90
	   |-- fabric-networking-v0 0.3.29+df3654b390
	   |-- fabric-object-builder-api-v1 4.2.2+d8ef690890
	   |-- fabric-particles-v1 1.1.0+ee641e7390
	   |-- fabric-recipe-api-v1 1.0.2+413cbbc790
	   |-- fabric-registry-sync-v0 0.9.33+9244241690
	   |-- fabric-renderer-api-v1 1.2.1+1adbf27790
	   |-- fabric-renderer-indigo 0.8.0+1adbf27790
	   |-- fabric-renderer-registries-v1 3.2.25+df3654b390
	   |-- fabric-rendering-data-attachment-v1 0.3.19+6e0787e690
	   |-- fabric-rendering-fluids-v1 3.0.11+4d0d570390
	   |-- fabric-rendering-v0 1.1.28+df3654b390
	   |-- fabric-rendering-v1 1.13.0+526f2c6790
	   |-- fabric-resource-conditions-api-v1 2.1.2+aae9039d90
	   |-- fabric-resource-loader-v0 0.8.4+edbdcddb90
	   |-- fabric-screen-api-v1 1.0.32+4d0d570390
	   |-- fabric-screen-handler-api-v1 1.3.8+1cc24b1b90
	   |-- fabric-sound-api-v1 1.0.2+c4f28df590
	   |-- fabric-textures-v0 1.0.24+aeb40ebe90
	   |-- fabric-transfer-api-v1 2.1.6+413cbbc790
	   \-- fabric-transitive-access-wideners-v1 1.3.3+08b73de490
	- fabric-language-kotlin 1.10.14+kotlin.1.9.20
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.20
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.20
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.20
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.20
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.23.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.1
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.1
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.1
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.1
	- fabricloader 0.15.6
	   \-- mixinextras 0.3.2
	- fabricskyboxes 0.7.2+mc1.19.2
	- fastquit 2.1.0+1.19-1.19.2
	- ferritecore 5.0.3
	- forgeconfigapiport 4.2.11
	   |-- com_electronwill_night-config_core 3.6.5
	   \-- com_electronwill_night-config_toml 3.6.5
	- geckolib3 3.1.40
	   \-- com_eliotlash_mclib_mclib 20
	- hexal 0.2.18
	   |-- fiber 0.23.0-2
	   |-- lib39-core 1.5.0-pre2+1.19.2
	   |-- lib39-phantom 1.5.0-pre2+1.19.2
	   \-- serialization_hooks 0.3.24
	- hexcasting 0.10.3
	   |-- reach-entity-attributes 2.3.0
	   \-- serialization_hooks 0.3.24
	- hexgloop 1.19.2-0.2.0
	   |-- org_jblas_jblas 1.2.5
	   |-- org_joml_joml 1.10.5
	   |-- reach-entity-attributes 2.3.0
	   \-- serialization_hooks 0.3.24
	- hexkinetics 0.7.2
	   |-- fiber 0.23.0-2
	   \-- serialization_hooks 0.3.24
	- hexlink 2.2.4
	- hexresearch 1.0.1
	   |-- reach-entity-attributes 2.3.0
	   \-- serialization_hooks 0.3.24
	- hextweaks 3.2.3
	- hexxy-dimensions 1.1.1
	- iceberg 1.0.46
	- immersive_portals 2.3.2
	   |-- imm_ptl_core 2.3.2
	   \-- q_misc_util 2.3.2
	- indium 1.0.9+mc1.19.2
	- inventoryessentials 5.4.0
	- inventorytabs 0.9.beta-1.19.x
	- itemborders 1.1.6
	- jade 8.7.3
	- java 17
	- jei 11.6.0.1018
	- jeresources 1.2.3.243
	- justenoughprofessions 2.0.2
	- kleeslabs 12.3.0
	- krypton 0.2.1
	   \-- com_velocitypowered_velocity-native 3.1.2-SNAPSHOT
	- leavesbegone 4.0.1
	- letmedespawn fabric-1.0.2
	- lithium 0.11.1
	- lootr 0.4.27.67
	- make_bubbles_pop 0.2.1-fabric
	- mediaworks 1.0.6
	   |-- extensibleenums 4.0.0
	   |-- reach-entity-attributes 2.3.0
	   \-- serialization_hooks 0.3.24
	- memoryleakfix 1.1.5
	- minecraft 1.19.2
	- modernfix 5.13.0+mc1.19.2
	   \-- mixinextras 0.3.2
	- modmenu 4.2.0-beta.2
	- modmenu-badges-lib 2023.4.1
	- morechathistory 1.3.0
	- moreiotas 0.0.4
	   |-- fiber 0.23.0-2
	   \-- serialization_hooks 0.3.24
	- mousetweaks 2.22
	- naturescompass 1.19.2-2.1.0-fabric
	- nicer-skies 1.3.0
	- nochatreports 1.19.2-v1.13.12
	- oneironaut 0.2.3
	   |-- reach-entity-attributes 2.3.0
	   \-- serialization_hooks 0.3.24
	- overflowingbars 4.0.1
	- patchouli 1.19.2-77-FABRIC
	   \-- fiber 0.23.0-2
	- paucal 0.5.0
	   \-- fiber 0.23.0-2
	- pehkui 3.7.12+1.14.4-1.20.4
	   \-- kanos_config 0.4.1+1.14.4-1.19.4
	- pickupnotifier 4.2.4
	- player-animator 1.0.2
	- polymorph 0.46.5+1.19.2
	   |-- cardinal-components-base 5.0.2
	   |-- cardinal-components-block 5.0.2
	   |-- cardinal-components-entity 5.0.2
	   |-- cardinal-components-item 5.0.2
	   \-- spectrelib 0.12.6+1.19.2
	- presencefootsteps 1.6.4
	   \-- kirin 1.11.1
	- prism 1.0.3
	- puzzleslib 4.4.3
	   |-- cardinal-components-base 5.0.2
	   |-- cardinal-components-block 5.0.2
	   |-- cardinal-components-chunk 5.0.2
	   |-- cardinal-components-entity 5.0.2
	   \-- cardinal-components-world 5.0.2
	- reacharound 1.1.2
	- reeses-sodium-options 1.6.4+mc1.19.2-build.93
	- shimmer 1.19.2-0.1.14
	   \-- cloth-config 8.2.88
	        \-- cloth-basic-math 0.6.1
	- shutupmojang 1.2.1
	- sleepwarp 2.0.0+1.19.2
	- smoothboot 1.19-1.7.1
	- smoothswapping 0.9.2
	- sodium 0.4.4+build.18
	- sodium-extra 0.4.16+mc1.19.2-build.90
	   \-- caffeineconfig 1.0.0+1.17
	- sound_physics_remastered 1.19.2-1.3.1
	- spawnanimations 1.9.4+mod
	- starlight 1.1.1+fabric.ae22326
	- status-effect-bars 1.0.1
	- terrablender 2.0.1.166
	- tipsmod 8.0.27
	- totemcounter 1.2.4+mc1.19.2
	- travelerstitles 1.19.2-Fabric-3.1.0
	- trinkets 3.4.2
	- ukulib 0.6.1+1.19.2
	   |-- com_moandjiezana_toml_toml4j 0.7.2
	   \-- gs_mclo_java_mclogs-java 2.1.1
	- veinmining 1.1.3+1.19.2
	   \-- spectrelib 0.12.6+1.19.2
	- villagernames 7.3
	- visuality 0.5.6
	- visualworkbench 4.2.4
	- wnboi 0.0.4
	- xaerominimap 23.9.7
	- xaeroworldmap 1.37.8
	- yet-another-config-lib 2.2.0-for-1.19.2
	- yungsapi 1.19.2-Fabric-3.8.10
	   \-- org_javassist_javassist 3.28.0-GA
	- yungsextras 1.19.2-Fabric-3.1.0
[17:26:02] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/{COMPUTER_USERNAME}/AppData/Roaming/com.modrinth.theseus/meta/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[17:26:02] [main/INFO]: Compatibility level set to JAVA_16
[17:26:02] [main/INFO]: Compatibility level set to JAVA_17
[17:26:03] [main/WARN]: Reference map 'hexkinetics.mixins.refmap.json' for hexkineticsplat.mixins.json could not be read. If this is a development environment you can ignore this message
[17:26:03] [main/WARN]: Reference map 'hexkinetics.mixins.refmap.json' for hexkinetics.mixins.json could not be read. If this is a development environment you can ignore this message
[17:26:03] [main/WARN]: Reference map 'hextweaks-fabric-refmap.json' for hextweaks.mixins.json could not be read. If this is a development environment you can ignore this message
[17:26:03] [main/WARN]: Reference map 'JustEnoughResources-Fabric-1.19.2-refmap.json' for jeresources.mixins.json could not be read. If this is a development environment you can ignore this message
[17:26:03] [main/WARN]: Reference map 'JustEnoughProfessions-fabric-1.19.2-refmap.json' for justenoughprofessions.fabric.mixins.json could not be read. If this is a development environment you can ignore this message
[17:26:03] [main/INFO]: Loaded configuration file for Lithium: 114 options available, 2 override(s) found
[17:26:03] [main/WARN]: Reference map 'memoryleakfix-fabric-1.17+-fabric-refmap.json' for memoryleakfix-fabric.mixins.json could not be read. If this is a development environment you can ignore this message
[17:26:03] [main/INFO]: Loaded configuration file for ModernFix 5.13.0+mc1.19.2: 55 options available, 2 override(s) found
[17:26:03] [main/WARN]: Option 'mixin.bugfix.item_cache_flag' overriden (by mods [lithium]) to 'false'
[17:26:03] [main/WARN]: Option 'mixin.perf.thread_priorities' overriden (by mods [smoothboot]) to 'false'
[17:26:03] [main/INFO]: Applying Nashorn fix
[17:26:03] [main/WARN]: Reference map 'moreiotas.mixins.refmap.json' for moreiotasplat.mixins.json could not be read. If this is a development environment you can ignore this message
[17:26:03] [main/WARN]: Reference map 'moreiotas.mixins.refmap.json' for moreiotas.mixins.json could not be read. If this is a development environment you can ignore this message
[17:26:03] [main/WARN]: [Satin] Sodium is present, custom block renders may not work
[17:26:03] [main/WARN]: Reference map 'smoothswapping-fabric-refmap.json' for smoothswapping.mixins.json could not be read. If this is a development environment you can ignore this message
[17:26:03] [main/INFO]: Loaded configuration file for Sodium: 29 options available, 0 override(s) found
[17:26:03] [main/INFO]: Loaded configuration file for Sodium Extra: 28 options available, 0 override(s) found
[17:26:03] [main/WARN]: Reference map 'yungsextras.refmap.json' for yungsextras.mixins.json could not be read. If this is a development environment you can ignore this message
[17:26:03] [main/WARN]: Reference map 'yungsextras.refmap.json' for yungsextras_fabric.mixins.json could not be read. If this is a development environment you can ignore this message
[17:26:03] [main/ERROR]: Mixin prepare for mod hexlink failed preparing LootManagerMixin in hexlink.mixins.json: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException Critical problem: hexlink.mixins.json:LootManagerMixin from mod hexlink target net.fabricmc.fabric.api.resource.IdentifiableResourceReloadListener was loaded too early.
org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException: Critical problem: hexlink.mixins.json:LootManagerMixin from mod hexlink target net.fabricmc.fabric.api.resource.IdentifiableResourceReloadListener was loaded too early.
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readDeclaredTargets(MixinInfo.java:948) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:882) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:852) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:777) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:540) [sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) [sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) [sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) [sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) [fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) [fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) [fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) [fabric-loader-0.15.6.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) [?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Unknown Source) [?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) [fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) [fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) [fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) [fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) [fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.6.jar:?]
[17:26:03] [main/ERROR]: A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'essential-loader'!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.6.jar:?]
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'essential-loader'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) ~[fabric-loader-0.15.6.jar:?]
	... 2 more
Caused by: net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'preLaunch' provided by 'essential-loader'
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:56) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) ~[fabric-loader-0.15.6.jar:?]
	... 2 more
Caused by: java.lang.RuntimeException: Mixin transformation of gg.essential.loader.stage0.EssentialSetupPreLaunch failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.6.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) ~[fabric-loader-0.15.6.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [hexlink.mixins.json:LootManagerMixin from mod hexlink] from phase [DEFAULT] in config [hexlink.mixins.json] FAILED during PREPARE
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinPrepareError(MixinProcessor.java:585) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:543) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.6.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) ~[fabric-loader-0.15.6.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException: Critical problem: hexlink.mixins.json:LootManagerMixin from mod hexlink target net.fabricmc.fabric.api.resource.IdentifiableResourceReloadListener was loaded too early.
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readDeclaredTargets(MixinInfo.java:948) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:882) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:852) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:777) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:540) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.6.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) ~[fabric-loader-0.15.6.jar:?]
	... 2 more

**Comment by Jempasam** [comment]
I can't reproduce this error with only the same version of Hexlink, Fabric and FAPI.
There are too many mods to download.
I'll try something but I won't be able to verify that it works myself.

**Comment by Ang3l404** [comment]
I can send over a modpack if that would help.

**Comment by Jempasam** [comment]
Yes it would help a lot, thank you/

**Comment by Ang3l404** [comment]
[Morro 0.0.1.zip](https://github.com/Jempasam/Hexlink/files/14212652/Morro.0.0.1.zip)

**Comment by Jempasam** [comment]
Ok, after removing the mod "Blur", the issue is solved for your modpack.
Adding Blur to my personal modpack with hexlink don't cause the issue, it is caused by an interaction between multiple mods.

**Comment by Jempasam** [comment]
Having "Blur" and "Sodium" at the same time cause this issue.

**Comment by Jempasam** [comment]
The issue is solved by b959d21

**Comment by Jempasam** [comment]
You can download the last version of hexlink (2.2.5) and play with Blur and Sodium.
